spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: ksumatova178@gmail.com
    password: hayxdlobulrrcyop
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    protocol: smtps
    quartz:
      job-store-type: memory
  security:
    user:
      name: user
      password: user
  datasource:
    driverClassName: org.postgresql.Driver
    password: another
    url: jdbc:postgresql://localhost:5432/camunda
    username: antonsabalov
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: lab4
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      platform: postgres

camunda.bpm.admin-user:
  id: drukhary
  password: drukhary
